type Query  {
   greeting: String
   students: [Student]
   users: [User]
   studentById(id: ID!): Student
   setFavColor(color: ColorType):String
}

type Mutation {
    createStudent(collegeId: ID, firstName: String, lastName: String): String
    addStudent_returns_object(collegeId: ID, firstName: String, lastName: String): Student
    delStudent(sid: ID!): String
    updateStudent(stud: UpdationInput): String
}

input UpdationInput{
    id: ID!
    firstName: String
    lastName: String
    collegeId: String
}

type Student {
   id: ID!
   firstName: String
   lastName: String
   password: String
   fullName: String
   collegeId: String
   college: College
}

type College {
   id: ID!
   name: String
   location: String
   rating: Float
}

type User {
    id: ID!
    name: String
    username: String
    email: String
    phone: String
    website: String
    nickname: String
}

enum ColorType {
   RED
   BLUE
   GREEN
}
