type Query  {
   greeting: String,
   students: [Student],
   users: [User]
}

type Student {
   id:ID!
   firstName:String
   lastName:String
   password:String
   collegeId:String
}

type User {
    id: ID!
    name: String
    username: String
    email: String
    phone: String
    website: String
}
