type Query  {
   greeting: String
   students: [Student]
   users: [User]
   studentById(id: ID!): Student
}

type Student {
   id: ID!
   firstName: String
   lastName: String
   password: String
   fullName: String
   collegeId: String
}

type User {
    id: ID!
    name: String
    username: String
    email: String
    phone: String
    website: String
    nickname: String
}
